dev_addr: 127.0.0.1:3000
site_name: Django AWS Config
theme:
  name: material
  custom_dir: docs/overrides
  features:
      - announce.dismiss
      - content.tabs.link
      - content.action.edit
      - content.action.view
      - content.code.annotate
      - content.code.copy
      # - content.code.select
      # - content.footnote.tooltips
      # - content.tabs.link
      - content.tooltips
      # - header.autohide
      # - navigation.expand
      - navigation.footer
      - navigation.indexes
      # - navigation.instant
      # - navigation.instant.prefetch
      # - navigation.instant.progress
      # - navigation.prune
      - navigation.sections
      - navigation.tabs
      # - navigation.tabs.sticky
      - navigation.top
      - navigation.tracking
      - search.highlight
      - search.share
      - search.suggest
      - toc.follow
      # - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - attr_list
  - abbr
  - toc
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

repo_name: django-aws-config
repo_url: https://github.com/Strelix/django-aws-config

site_url: https://docs.strelix.org/django-aws-config/

site_description: Documentation for django-aws-config
site_author: treyww

nav:
  - AWS Config:
      - index.md
  - User Guide:
      - user-guide/getting-started/index.md
      - Installation: user-guide/getting-started/installation.md
      - Settings: user-guide/getting-started/settings.md
      - Usage:
          - Core Usage: user-guide/getting-started/usage/core.md
          - Dataclasses: user-guide/getting-started/usage/dataclasses.md
          - Decorator Usage: user-guide/getting-started/usage/decorators.md
          - Middleware: user-guide/getting-started/usage/middleware.md
  - Contributing:
      - contributing/index.md
      - Setup project: contributing/setup.md
      - Style guide: contributing/style-guide.md
      - Github Issues: contributing/gh-issues.md
      - Ask for help: contributing/ask.md
      - Writing Documentation: contributing/writing-documentation.md
      - Translations: contributing/translations.md
      - Github Project Board: contributing/gh-board.md
      - Motivation: contributing/motivation.md
      - Development Progression: contributing/development-progression.md
      - Taking on a lead position: contributing/lead-position.md
  - Changelog:
      - changelog.md

extra:
  analytics:
    provider: custom
    property: !ENV UMAMI_PAGE_URL
    id: !ENV UMAMI_WEBSITE_ID
  version:
    provider: mike